from flask import Flask, render_template

app = Flask(__name__)

# ==================== БАЗА ДАННЫХ ФИЛЬМОВ ====================
MOVIES = [
    {
        "id": 1, "type": "cartoon", "title": "Волшебный клад",
        "original_title": "Волшебный клад",
        "year": 1950,
        "genre": "мультфильм, детский, короткометражка, фэнтези",
        "age": "12+",
        "poster_emoji": "✨",
        "poster_url": "https://avatars.mds.yandex.net/get-ott/1648503/2a000001985419d46aaf1b797ac20989b9d8/600x900",
        "director": "Дмитрий Бабиченко",
        "writers": "Дмитрий Бабиченко, Павел Маляревский",
        "producer": "—",
        "operator": "Михаил Друян",
        "composer": "Карэн Хачатурян",
        "artist": "Григорий Козлов",
        "editor": "Лидия Кякшт",
        "dvd_release": "19 января 2009, «Азимут»",
        "actors": "Владимир Балашов, Эраст Гарин, Владимир Грибков, Наталья Гицерот, Александра Панова",
        "country": "СССР",
        "duration": "20 мин.",
        "rating": "7.1",
        "votes": "3 081",
        "slogan": "—",
        "description": "В далекие времена стада богача Галсана охранял пастух Баир. Однажды увидел он, как гриф схватил чудесную птицу, и спас ее, подстрелив хищника из лука. Закончилась его служба, и захотел он уйти, получив 16 монет, но жадный богач вычел с него за охромевшую кобылу и за сломанный кнут. Пастух не выдержал и огрел негодяя по башке сундуком. Слуги бросили его связанным в ущелье. Вот тогда и прилетела к нему чудесная птица.",
        "video": "https://youtu.be/9D-PYOqo0T8",
        "source": "YouTube"
    },
    {
        "id": 2, "type": "cartoon", "title": "Волшебная птица",
        "original_title": "Волшебная птица",
        "year": 1953,
        "genre": "мультфильм, детский, короткометражка",
        "age": "12+",
        "poster_emoji": "🐦",
        "poster_url": "https://m.media-amazon.com/images/M/MV5BZDIxNjY1ZGEtMzRlMy00ZGRmLWFkZWEtZDBhMzU2NTljNjRjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        "director": "Виктор Громов",
        "writers": "Николай Рожков",
        "producer": "—",
        "operator": "Н. Соколова, Александр Астафьев",
        "composer": "Анатолий Новиков",
        "artist": "Александр Винокуров, Константин Чикин, Геннадий Филиппов",
        "editor": "В. Егорова",
        "dvd_release": "—",
        "actors": "Анастасия Зуева, Инесса Дровосекова, Дмитрий Павловский, Николай Никитич, Борис Терентьев",
        "country": "СССР",
        "duration": "19 мин.",
        "rating": "7.4",
        "votes": "1 234",
        "slogan": "—",
        "description": "По мотивам русской народной сказки. Славится Наталья из Озерска не только красотой своей, но и рукоделием. И только тот, кто сравниться сможет с ней в мастерстве, диковинку преподнесет, под венец поведет красавицу.",
        "video": "https://youtu.be/bySQdGeINfM",
        "source": "YouTube"
    },
    {
        "id": 3, "type": "cartoon", "title": "Дядюшка Ау",
        "original_title": "Дядюшка Ау",
        "year": 1979,
        "genre": "мультфильм, короткометражка",
        "age": "0+",
        "poster_emoji": "👻",
        "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/7cc9abba-bff0-4d96-bc7f-2d1935625d82/600x900",
        "director": "Иосиф Доукша, Майя Бузинова",
        "writers": "Эдуард Успенский, Ханну Мякеля",
        "producer": "—",
        "operator": "Александр Жуковский",
        "composer": "Александр Журбин",
        "artist": "Ольга Гвоздёва",
        "editor": "Любовь Георгиева",
        "dvd_release": "29 апреля 2010, «Флагман-Трейд»",
        "actors": "Александр Граве, Василий Ливанов, Татьяна Решетникова, Владимир Ферапонтов, Михаил Лобанов",
        "country": "СССР",
        "duration": "~19 мин. (серия)",
        "rating": "7.9",
        "votes": "2 456",
        "slogan": "—",
        "description": "Забавный мультфильм о лесном домовёнке по имени Ау, который живёт в лесу и постоянно попадает в смешные ситуации. Он очень одинок и хочет найти друзей, но из-за своего скверного характера всё время остаётся один.",
        "seasons": {
            1: {"title": "1 серия", "video_url": "https://drive.google.com/file/d/1A1oOkfV-RDndBOEhI9f9LV7n-zGnGFNL/preview"},
            2: {"title": "2 серия", "video_url": "https://drive.google.com/file/d/1DSyF1XFNLUKzPMzLVKR0CL61u7V6A9ws/preview"},
            3: {"title": "3 серия", "video_url": "https://drive.google.com/file/d/1yaJWDW3c-4JB0axkLOirX6OyAh-ewGDw/preview"}
        },
        "video": "https://drive.google.com/file/d/1A1oOkfV-RDndBOEhI9f9LV7n-zGnGFNL/preview",
        "source": "Google Диск",
        "type": "series"
    },
    {
        "id": 4, "type": "cartoon", "title": "Самый главный",
        "original_title": "Самый главный",
        "year": 1970,
        "genre": "мультфильм, короткометражка",
        "age": "6+",
        "poster_emoji": "⭐",
        "poster_url": "/static/Постер1.png",
        "director": "Витольд Бордзиловский",
        "writers": "Николай Эрдман, Аркадий Снесарев, Борис Тихомолов",
        "producer": "—",
        "operator": "Елена Петрова",
        "composer": "—",
        "artist": "Валентина Василенко",
        "editor": "Любовь Георгиева",
        "dvd_release": "—",
        "actors": "Зинаида Нарышкина, Алексей Грибов, Сергей Мартинсон, Николай Александрович, Владимир Раутбарт",
        "country": "СССР",
        "duration": "19 мин.",
        "rating": "7.4",
        "votes": "0",
        "slogan": "—",
        "description": "Фильм в сказочной форме рассказывает о том, что труд является самым главным объединяющим началом в дружбе людей разных профессий.",
        "video": "https://youtu.be/fvvHcdMditI",
        "source": "YouTube"
    },
    {
        "id": 5, "type": "cartoon", "title": "Высокая горка",
        "original_title": "Высокая горка",
        "year": 1951,
        "genre": "мультфильм, детский, короткометражка",
        "age": "0+",
        "poster_emoji": "🐦",
        "poster_url": "/static/Постер2.png",
        "director": "Леонид Амальрик, Владимир Полковников",
        "writers": "Михаил Вольпин, Григорий Колтунов, Виталий Бианки",
        "producer": "—",
        "operator": "Михаил Друян",
        "composer": "Виктор Оранский",
        "artist": "Александр Трусов",
        "editor": "Александра Фирсова",
        "dvd_release": "12 февраля 2009, «Русское счастье»",
        "actors": "Ирина Гошева, Георгий Вицин, Анастасия Зуева, Клементина Ростовцева",
        "country": "СССР",
        "duration": "20 мин.",
        "rating": "8.0",
        "votes": "0",
        "slogan": "—",
        "description": "Непутевый воробей Чик вечно втягивает свою Чирику в неприятности. Классический мультфильм по Виталию Бианки.",
        "video": "https://youtu.be/QJdngyi6OdM",
        "source": "YouTube"
    },
    {
        "id": 6, "type": "series", "title": "Фитиль",
        "original_title": "Фитиль",
        "year": 1962,
        "genre": "короткометражка, комедия",
        "age": "12+",
        "poster_emoji": "🎬",
        "poster_url": "/static/Постер3.png",
        "director": "Георгий Данелия, Леонид Гайдай, Александр Митта, ...",
        "writers": "Сергей Михалков, Михаил Жванецкий, Виктория Токарева, ...",
        "producer": "—",
        "operator": "Марк Цирульников, Геннадий Немых, Геннадий Лысяков",
        "composer": "Геннадий Савельев",
        "artist": "—",
        "editor": "—",
        "dvd_release": "—",
        "actors": "Николай Парфёнов, Борис Новиков, Петр Щербаков, Юрий Волынцев, Георгий Бурков, Борис Гитин, Виктор Филиппов, Евгений Леонов, Ролан Быков, Михаил Пуговкин",
        "country": "СССР",
        "duration": "~10 мин. (выпуск)",
        "rating": "8.5",
        "votes": "0",
        "slogan": "—",
        "description": "«Фитиль» — сатирический художественный киножурнал, который выпускался в СССР и России с 1962 по 2008 год.",
        "seasons": {
            1: {"title": "Выпуск 1", "video_url": "https://youtu.be/22N_3zI4Nkc"},
            2: {"title": "Выпуск 2", "video_url": "https://youtu.be/IwmnIudQcUQ"},
            3: {"title": "Выпуск 3", "video_url": "https://youtu.be/-vaDeBCATyU"},
            4: {"title": "Выпуск 4", "video_url": "https://youtu.be/UCw50Zzlwuo"},
            5: {"title": "Выпуск 5", "video_url": "https://youtu.be/zBbxD_4l5yw"},
            6: {"title": "Выпуск 6", "video_url": "https://youtu.be/M8rbNcO3weY"}
        },
        "video": "https://youtu.be/22N_3zI4Nkc",
        "source": "YouTube",
        "type": "series"
    },
    {
        "id": 7, "type": "cartoon", "title": "Последняя невеста Змея Горыныча",
        "original_title": "Последняя невеста Змея Горыныча",
        "year": 1978,
        "genre": "мультфильм, детский, фэнтези, история, короткометражка",
        "age": "6+",
        "poster_emoji": "🐉",
        "poster_url": "https://avatars.mds.yandex.net/get-ott/200035/2a0000019854acf1bbcce150dc9ba9decc13/600x900",
        "director": "Роман Давыдов",
        "writers": "Владимир Данилов",
        "producer": "К. Антонов",
        "operator": "Борис Котов",
        "composer": "Владимир Кривцов",
        "artist": "Владимир Морозов",
        "editor": "Елена Тертычная",
        "dvd_release": "—",
        "actors": "Герман Качин, Владимир Басов, Юрий Пузырёв, Людмила Касаткина, Валентина Телегина, Клара Румянова, Роман Филиппов, Ольга Громова, Александр Баранов, Юрий Хржановский",
        "country": "СССР",
        "duration": "18 мин.",
        "rating": "7.5",
        "votes": "0",
        "slogan": "—",
        "description": "Солдат вызволяет царевну из лап чудища-оборотня. Фантазия на тему народных сказок от режиссёра «Маугли».",
        "video": "https://vkvideo.ru/video_ext.php?oid=-234885061&id=456239097&hash=f53e4556405283da",
        "source": "VK Video"
    },
    {
        "id": 8, "type": "cartoon", "title": "Падал прошлогодний снег",
        "original_title": "Падал прошлогодний снег",
        "year": 1983,
        "genre": "мультфильм, фэнтези, короткометражка, комедия",
        "age": "0+",
        "poster_emoji": "❄️",
        "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/10703959/d5a830cd-e916-449d-a15e-439fb8510cfb/600x900",
        "director": "Александр Татарский",
        "writers": "Сергей Иванов",
        "producer": "Зинаида Сараева",
        "operator": "Иосиф Голомб",
        "composer": "Григорий Гладков",
        "artist": "Людмила Танасенко",
        "editor": "Любовь Георгиева",
        "dvd_release": "16 декабря 2008, «Мьюзик-Трейд»",
        "premiere": "31 декабря 1983",
        "actors": "Станислав Садальский",
        "country": "СССР",
        "duration": "20 мин.",
        "rating": "8.8",
        "votes": "0",
        "slogan": "—",
        "description": "Мужчину в самом расцвете сил жена отправила за елкой. Афористичная пластилиновая сказка Александра Татарского.",
        "video": "https://drive.google.com/file/d/1tabd-t9WZhevxlFh2jUB217sccXgrFkq/preview",
        "ad_video": "https://youtu.be/-kHD7OC9IBU",
        "source": "Google Диск + Реклама",
        "is_new_year": True
    },
    {
        "id": 9, "type": "cartoon", "title": "Школа снеговиков",
        "original_title": "Школа снеговиков",
        "year": 2009,
        "genre": "короткометражка, мультфильм",
        "age": "0+",
        "poster_emoji": "⛄",
        "poster_url": "/static/Постер4.png",
        "director": "Александр Маркелов",
        "writers": "Андрей Усачёв",
        "producer": "Акоп Киракосян",
        "operator": "—",
        "composer": "Александр Пинегин",
        "artist": "Александр Маркелов",
        "editor": "Ольга Василенко",
        "dvd_release": "—",
        "actors": "Александр Пожаров, Алексей Емцов, Лариса Брохман",
        "country": "Россия",
        "duration": "13 мин.",
        "rating": "—",
        "votes": "0",
        "slogan": "—",
        "description": "Фильм состоит из двух мультфильмов – «Дед Мороз из Дедморозовки» и «Хоккей в Дедморозовке».",
        "seasons": {
            1: {"title": "1 серия", "video_url": "https://drive.google.com/file/d/1Ys-OOAb386vjiJyu9RfKhBqMb9FCuSKl/preview"},
            2: {"title": "2 серия", "video_url": "https://drive.google.com/file/d/1r06Ql4BQSGT2Q48JLlWY7vQqLPWBVomq/preview"}
        },
        "video": "https://drive.google.com/file/d/1Ys-OOAb386vjiJyu9RfKhBqMb9FCuSKl/preview",
        "source": "Google Диск",
        "type": "series",
        "is_new_year": True
    },
    {
        "id": 10, "type": "cartoon", "title": "В лесу родилась ёлочка",
        "original_title": "В лесу родилась ёлочка",
        "year": 1972,
        "genre": "мультфильм, короткометражка",
        "age": "0+",
        "poster_emoji": "🎄",
        "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/5d5e5e95-eaf0-46f6-8217-162c534158d5/600x900",
        "director": "Борис Бутаков",
        "writers": "Борис Бутаков",
        "producer": "М. Чичельницкий",
        "operator": "Артур Франго",
        "composer": "В. Свешников",
        "artist": "Наталья Богомолова",
        "editor": "Нина Бутакова",
        "dvd_release": "27 ноября 2008, «Мьюзик-Трейд»",
        "premiere": "—",
        "actors": "Анатолий Кубацкий",
        "country": "СССР",
        "duration": "7 мин.",
        "rating": "7.2",
        "votes": "6 616",
        "slogan": "—",
        "description": "Мальчик показывает друзьям-животным фильм про новогоднюю ёлочку.",
        "video": "https://drive.google.com/file/d/1Xa19Sb0lSj6Xjh7azPooibdJ1dH49zt3/preview",
        "source": "Google Диск",
        "is_new_year": True
    },
    {
        "id": 11, "type": "cartoon", "title": "Новогодняя песенка Деда Мороза",
        "original_title": "Новогодняя песенка Деда Мороза",
        "year": 1982,
        "genre": "мультфильм, короткометражка",
        "age": "6+",
        "poster_emoji": "🎄",
        "poster_url": "/static/Постер5.png",
        "director": "Александр Татарский",
        "writers": "Эдуард Успенский",
        "producer": "—",
        "operator": "Иосиф Голомб",
        "composer": "Александр Журбин",
        "artist": "Людмила Танасенко",
        "editor": "—",
        "dvd_release": "—",
        "actors": "Владимир Басов, Станислав Садальский",
        "country": "СССР",
        "duration": "4 мин.",
        "rating": "6.5",
        "votes": "0",
        "slogan": "—",
        "description": "Дед Мороз и Снеговик придумывают душевный тост.",
        "video": "https://drive.google.com/file/d/1TDUVFx4VjzhDhTfUucfQb39fXmiJ9wRe/preview",
        "source": "Google Диск",
        "is_new_year": True
    },
    {
        "id": 12, "type": "cartoon", "title": "Смешарики. Азбука мобильного этикета",
        "original_title": "Смешарики. Азбука мобильного этикета",
        "year": 2011,
        "genre": "короткометражка, мультфильм, детский",
        "age": "0+",
        "poster_emoji": "📱",
        "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/10812607/fd13f0c7-f9f7-435f-a502-e4df46bf102a/600x900",
        "director": "Николай Кожаев",
        "writers": "—",
        "producer": "Илья Попов",
        "operator": "—",
        "composer": "—",
        "artist": "—",
        "editor": "—",
        "dvd_release": "—",
        "actors": "—",
        "country": "Россия",
        "duration": "1 мин.",
        "rating": "—",
        "votes": "0",
        "slogan": "—",
        "description": "Смешарики рассказывают о правилах, которые должен знать владелец телефона.",
        "video": "https://youtu.be/njC6eTQh9rk",
        "source": "YouTube",
        "type": "cartoon",
        "seasons": {
            1: {"title": "Азбука мобильного этикета", "video_url": "https://youtu.be/njC6eTQh9rk"}
        }
    },
    {
        "id": 13, "type": "cartoon", "title": "Мисс Новый год",
        "original_title": "Мисс Новый год",
        "year": 1991,
        "genre": "мультфильм, короткометражка",
        "age": "6+",
        "poster_emoji": "👑",
        "poster_url": "https://avatars.mds.yandex.net/get-ott/224348/2a0000019854ff32f4968eb2739adc942d95/600x900",
        "director": "Владимир Арбеков",
        "writers": "Виталий Злотников",
        "producer": "Нина Соколова",
        "operator": "Кабул Расулов",
        "composer": "Нина Савичева",
        "artist": "Татьяна Колюшева, Анна Атаманова, Николай Митрохин",
        "editor": "Галина Смирнова",
        "dvd_release": "—",
        "actors": "Ирина Муравьёва, Ирина Карташёва, Юрий Пузырёв, Александра Турган, Вячеслав Богачёв, Анатолий Баранцев",
        "country": "СССР",
        "duration": "9 мин.",
        "rating": "6.9",
        "votes": "0",
        "slogan": "—",
        "description": "Мама-ворона помогает дочке обманом выиграть конкурс красоты. Мультфильм о том, как нужно исправлять ошибки.",
        "video": "https://drive.google.com/file/d/1CksPjJbDzkevt7FTlNHmDcxoWH_U38tV/preview",
        "source": "Google Диск",
        "type": "cartoon",
        "is_new_year": True
    },
    {
        "id": 14, "type": "cartoon", "title": "Два богатыря",
        "original_title": "Два богатыря",
        "year": 1989,
        "genre": "мультфильм, детский, фэнтези, приключения, короткометражка",
        "age": "6+",
        "poster_emoji": "⚔️",
        "poster_url": "https://avatars.mds.yandex.net/get-ott/13051577/2a0000019854b2ac7234061d22590a3d9cc2/600x900",
        "director": "Александр Давыдов",
        "writers": "Заурия Нурумбетова, Тамара Чуганова",
        "producer": "Лилиана Монахова",
        "operator": "Людмила Крутовская",
        "composer": "Нина Савичева",
        "artist": "Елизавета Жарова",
        "editor": "Елена Белявская",
        "dvd_release": "—",
        "actors": "Дмитрий Полонский, Александр Малов, Наталия Ченчик, Людмила Гнилова, Мария Виноградова, Павел Смеян, Владимир Степин",
        "country": "СССР",
        "duration": "10 мин.",
        "rating": "8.0",
        "votes": "0",
        "slogan": "—",
        "description": "Храбрые богатыри Иван и Батыр меняются местами. Приключения на основе русского и казахского фольклора.",
        "video": "https://drive.google.com/file/d/1jlmaxHEibD6i7nCG6bsqutwVOWm7jW5J/preview",
        "source": "Google Диск",
        "type": "cartoon"
    },
    {
        "id": 15, "type": "cartoon", "title": "Межа",
        "original_title": "Межа",
        "year": 1967,
        "genre": "мультфильм, детский, короткометражка",
        "age": "6+",
        "poster_emoji": "⚔️",
        "poster_url": "https://www.kino-teatr.ru/movie/posters/big/3/8/101783.jpg",
        "director": "Вячеслав Котёночкин",
        "writers": "Юрий Киршон",
        "producer": "Федор Иванов",
        "operator": "Елена Петрова",
        "composer": "Виктор Купревич",
        "artist": "Светозар Русаков",
        "editor": "Татьяна Сазонова",
        "dvd_release": "—",
        "actors": "Анатолий Папанов, Евгений Весник, Василий Алчевский",
        "country": "СССР",
        "duration": "20 мин.",
        "rating": "8.0",
        "votes": "0",
        "slogan": "—",
        "description": "Смекалистый солдат спасает родную землю от Змея Горыныча и жадного царя. Сказка от режиссера «Ну, погоди!».",
        "video": "https://drive.google.com/file/d/1VoTGMAXuxPjGgkuQ1RYRweSHv1vf01Vi/preview",
        "source": "Google Диск",
        "type": "cartoon"
    }
]

ALL_GENRES = [
    "боевик", "вестерн", "детектив", "драма", "история", "комедия", "криминал",
    "мелодрама", "мультфильм", "приключения", "семейный", "спорт", "триллер",
    "ужасы", "фантастика", "фэнтези", "артхаус", "биография", "документальный",
    "короткометражка", "мюзикл", "нуар", "реальное ТВ", "ток-шоу", "фильм-нуар", "детский", "сказка"
]

@app.route('/')
def index():
    return render_template('index.html', movies=MOVIES, genres=ALL_GENRES)

if __name__ == '__main__':
    app.run(debug=False, host='0.0.0.0', port=5000)
